In [13]:
import numpy as np
from numpy.linalg import norm
np.set_printoptions(precision=10)

In [14]:
def Cholesky(A: np.array):
    m, _ = A.shape
    if m != _: return
    if not (A.T == A).all(): return
    R = np.triu(A)
    for k in range(m):
        if R[k, k] <= 0: 
            raise np.linalg.LinAlgError()
        R[k, k:] = R[k, k:]/np.sqrt(R[k, k])
        for i in range(k+1, m):
            R[i, i:] = R[i, i:] - R[k, i:]*R[k, i]
    return R

In [15]:
def gausspivot(A: np.array):
    m = A.shape[0]
    assert m == A.shape[1]
    
    L = np.identity(m)
    P = np.identity(m)
    U = A.copy()
    for k in range(m-1):
        i_max = np.argmax(A[k:, k]**2) + k # find arg max
        # swapping U P L        
        P[[k, i_max]] = P[[i_max, k]] 
        U[[k, i_max], k:] = U[[i_max, k], k:]
        L[[k, i_max], :k] = L[[i_max, k], :k]
        for i in range(k+1, m):
            L[i:, k] = U[i, k]/U[k, k]
            U[i] -= L[i, k]*U[k]
            
    return (L, U, P)

In [16]:
A = np.array([[10, 3, -1, -3, -9], 
              [3, 6, -5, -3, -1], 
              [-1, -5, 9, 2, -1], 
              [-3, -3, 2, 2, 2], 
              [-9, -1, -1, 2, 9]], dtype=np.float128)

In [17]:
L, U, _ = gausspivot(A)
print(L, '\n\n', U)
print('Delta1: ', norm(L@U - A)/norm(A))

[[ 1.            0.            0.            0.            0.          ]
 [ 0.3           1.            0.            0.            0.          ]
 [-0.1          -0.9215686275  1.            0.            0.          ]
 [-0.3          -0.4117647059 -0.0515021459  1.            0.          ]
 [-0.9           0.3333333333 -0.0729613734 -0.0769230769  1.          ]] 

 [[ 1.0000000000e+01  3.0000000000e+00 -1.0000000000e+00 -3.0000000000e+00
  -9.0000000000e+00]
 [ 1.1102230246e-16  5.1000000000e+00 -4.7000000000e+00 -2.1000000000e+00
   1.7000000000e+00]
 [ 1.5782582213e-16 -2.3028454144e-16  4.5686274510e+00 -2.3529411765e-01
  -3.3333333333e-01]
 [-5.7178868221e-17 -1.3133922746e-16  1.5016200089e-17  2.2317596567e-01
  -1.7167381974e-02]
 [ 1.9215398503e-16 -1.6015334091e-16 -1.3927827908e-18 -9.4190063735e-19
   3.0769230769e-01]]
Delta1:  5.224497803497941143e-20


In [18]:
R = Cholesky(A)
print(R)
print('Delta2: ', norm(R.T@R - A)/norm(A))

[[ 3.1622776602  0.9486832981 -0.316227766  -0.9486832981 -2.8460498942]
 [ 0.            2.2583179581 -2.081194981  -0.9298956298  0.7527726527]
 [ 0.            0.            2.1374347829 -0.1100824781 -0.1559501773]
 [ 0.            0.            0.            0.4724150354 -0.0363396181]
 [ 0.            0.            0.            0.            0.5547001962]]
Delta2:  4.7866666924387177493e-20
