In [1]:
import numpy as np
from numpy.linalg import qr, norm
np.set_printoptions(precision=10, linewidth=120)

In [2]:
def qralgshift(A, eps):
    m, _  = A.shape
    assert m == _
    
    I = np.identity(m, dtype='float64')
    eigvec = np.identity(m, dtype='float64')
    mu = A[-1, -1]
    
    i = 0
    error = norm(A - np.diag(np.diag(A)))
    while (error > eps):
        Q, R = qr(A - mu * I)
        A = R @ Q + mu * I
        eigvec = eigvec @ Q
        error = norm(A - np.diag(np.diag(A)))
        
    return eigvec, A

In [3]:
def hessenberg(A):
    m, _ = A.shape
    assert m == _
    
    Q = np.identity(m, dtype='float64')
    
    for k in range(m - 2):
        x = - A[k+1:, k].copy()
        x[0] -= np.sign(x[0]) * norm(x)
        x /= norm(x)
        
        A[k+1:, k:] -= 2 * np.outer(x, (x @ A[k+1:, k:]))
        A[:, k+1:] -= 2 * np.outer((A[:, k+1:] @ x), x)
        Q[k+1:, :] -= 2 * np.outer(x, (x @ Q[k+1:, :]))
    
    return Q, A

In [4]:
eps = 10 ** -6
A = np.array([[2,6,4,-4,-5,10],
              [6,12,-2,9,5,9],
              [4,-2,0,-1,-3,14],
              [-4,9,-1,10,-6,8],
              [-5,5,-3,-6,2,8],
              [10,9,14,8,8,0]], dtype='float64')

In [5]:
print('Q: ')
print(*qralgshift(A, eps),sep='\n\n\u039B: \n')

Q: 
[[-0.2935021675  0.3357007469 -0.4371317164  0.1448671572 -0.4957230744 -0.5859603135]
 [-0.6132228382  0.0045245038  0.2708186545 -0.3913505274  0.4866595247 -0.4007515536]
 [-0.2373443004  0.4267855626 -0.4842008572  0.3391237572  0.5333190779  0.3572633972]
 [-0.4133131051  0.2947209925  0.626746332   0.4275441811 -0.3046940188  0.271787375 ]
 [-0.1031167136  0.4118699634 -0.1021878861 -0.7261506202 -0.3000324569  0.4381478223]
 [-0.547741848  -0.6698069056 -0.3128407263  0.0276513803 -0.2239061888  0.3202650105]]

Λ: 
[[ 2.9043400702e+001 -2.3478931990e-015  8.9421429290e-015  9.1286119148e-015 -3.4828587169e-015  3.6076977091e-015]
 [-1.0437295501e-019 -2.2432515106e+001 -1.0452182181e-015  3.3809911654e-015  2.1795484539e-015 -2.3012852244e-015]
 [ 5.3680937701e-055  2.4231605380e-034  1.4436399508e+001 -7.9256446591e-016  2.6248382831e-014  4.7319445578e-015]
 [-6.7013654476e-082 -2.7314429477e-061 -2.2841953615e-027  1.0321295034e+001  6.2931223503e-007 -4.8929589636e-015]


In [6]:
_, H = hessenberg(A)
print('Q: ')
print(*qralgshift(H, eps),sep='\n\n\u039B: \n')

Q: 
[[-0.3357007469 -0.4957230737 -0.2935021766 -0.5859603135 -0.4371317164 -0.1448671412]
 [ 0.5903938555  0.3982819756 -0.5713391126 -0.0756306263 -0.3913166515 -0.0867725091]
 [-0.5836320616  0.1295700438 -0.6422128172  0.4663483995  0.0816871251  0.0774228761]
 [-0.4171814224  0.6145163691  0.3858229834 -0.0467539216 -0.5286408129 -0.1335023597]
 [ 0.1550307936 -0.4475458329  0.1612528294  0.6437948163 -0.5788371293 -0.011896129 ]
 [-0.0062317234  0.0302335141  0.0113551194 -0.1295839305 -0.1860129647  0.9734091346]]

Λ: 
[[-2.2432515106e+001  2.2323452713e-017  1.8858731757e-018  5.3719746521e-015  2.3090442514e-015 -1.2476687902e-015]
 [ 1.1487668390e-100 -9.1616951592e+000 -7.0192735179e-007  5.7213276830e-015  3.2664993571e-015  3.2086326571e-016]
 [-2.3493151808e-124 -7.0192732481e-007  2.9043400702e+001  1.8009345661e-015  1.8567104303e-015 -1.8907805236e-015]
 [ 0.0000000000e+000 -2.6876741638e-228  1.3879201251e-204  3.7931150207e+000  2.4035640118e-015  3.3142041252e-015]
