In [31]:
import numpy as np
from numpy.linalg import norm, solve, LinAlgError

In [32]:
def poweriter(A, v0, eps, Nmax=10**3):
    m = A.shape[0]
    assert m == A.shape[1]
    assert m == v0.shape[0]
    
    v = v0 / norm(v0)
    l_o = v0.T @ A @ v0 # old lambda
    for i in range(Nmax):
        print('Lambda {0}: {1}\nv {0}: {2}\n'.format(i, l_o, v))
        v = A @ v
        v /= norm(v)
        l_n = v.T @ A @ v # new lambda
        if abs(l_n - l_o) < eps:
            return l_n, v
        l_o = l_n
    raise StopIteration('Max number of iteration reached')

In [33]:
def inverseiter(A, v0, mu, eps, Nmax=10**3):
    """The function does not add a check for the initial guess mu.
        It will fail if mu is the exact eigenvalue.
    """
    m = A.shape[0]
    assert m == A.shape[1]
    assert m == v0.shape[0]
    
    v = v0 / norm(v0)
    l_o = mu
    I = np.identity(m)
    for i in range(Nmax):
        print('Lambda {0}: {1}\nv {0}: {2}\n'.format(i, l_o, v))
        v = solve(A - mu * I, v)
        v /= norm(v)
        l_n = v.T @ A @ v # new lambda
        if abs(l_n - l_o) < eps:
            return l_n, v
        l_o = l_n
    raise StopIteration('Max number of iteration reached')

In [34]:
def rayleigh(A, v0, mu, eps, Nmax=10**3):
    """The function does not add a check for the initial guess mu.
        It will fail if mu is the exact eigenvalue.
    """
    m = A.shape[0]
    assert m == A.shape[1]
    assert m == v0.shape[0]
    
    v = v0 / norm(v0)
    l_o = mu
    I = np.identity(m)
    for i in range(Nmax):
        print('Lambda {0}: {1}\nv {0}: {2}\n'.format(i, l_o, v))
        v = solve(A - l_o * I, v)
        v /= norm(v)
        l_n = v.T @ A @ v # new lambda
        if abs(l_n - l_o) < eps:
            return l_n, v
        l_o = l_n
    raise StopIteration('Max number of iteration reached')

In [35]:
A = np.array([[2,6,4,-4,-5,10],
              [6,12,-2,9,5,9],
              [4,-2,0,-1,-3,14],
              [-4,9,-1,10,-6,8],
              [-5,5,-3,-6,2,8],
              [10,9,14,8,8,0]], dtype='float64')
v01 = np.array([1, 1, 1, 1, 1, 1], dtype='float64')
v02 = np.array([2, 5, 3, 0, -1, 1], dtype='float64')

In [36]:
# power iteration with v01 and tolerance 10^-6
l_p1_1, v_p1_1 = poweriter(A, v01, 10**-6)

Lambda 0: 130.0
v 0: [0.40824829 0.40824829 0.40824829 0.40824829 0.40824829 0.40824829]

Lambda 1: 25.093944790739087
v 1: [0.19396505 0.58189514 0.17904466 0.23872621 0.01492039 0.73109903]

Lambda 2: 26.68892430882623
v 2: [0.38196112 0.5826348  0.33585333 0.43645215 0.20538925 0.41130245]

Lambda 3: 27.626432593957183
v 3: [0.24151043 0.60064148 0.17628512 0.34096127 0.03750592 0.65739242]

Lambda 4: 28.191706057991016
v 4: [0.33988652 0.60523996 0.29487383 0.44005982 0.15774986 0.46116538]

Lambda 5: 28.532635851582512
v 5: [0.26095672 0.6084737  0.1966518  0.37782654 0.06241541 0.61346625]

Lambda 6: 28.73765203645719
v 6: [0.31984414 0.6109336  0.27084245 0.43289088 0.13500942 0.49546158]

Lambda 7: 28.86060748894485
v 7: [0.27359791 0.61150362 0.21221547 0.39404756 0.07857305 0.58713277]

Lambda 8: 28.934206623735413
v 8: [0.30897857 0.61258148 0.25709221 0.42597969 0.12207069 0.51654605]

Lambda 9: 28.97820583638576
v 9: [0.28152708 0.61257866 0.22218359 0.40232792 0.08843555 

In [37]:
# power iteration with v01 and tolerance 10^-10
l_p1_2, v_p1_2 = poweriter(A, v01, 10**-10)

Lambda 0: 130.0
v 0: [0.40824829 0.40824829 0.40824829 0.40824829 0.40824829 0.40824829]

Lambda 1: 25.093944790739087
v 1: [0.19396505 0.58189514 0.17904466 0.23872621 0.01492039 0.73109903]

Lambda 2: 26.68892430882623
v 2: [0.38196112 0.5826348  0.33585333 0.43645215 0.20538925 0.41130245]

Lambda 3: 27.626432593957183
v 3: [0.24151043 0.60064148 0.17628512 0.34096127 0.03750592 0.65739242]

Lambda 4: 28.191706057991016
v 4: [0.33988652 0.60523996 0.29487383 0.44005982 0.15774986 0.46116538]

Lambda 5: 28.532635851582512
v 5: [0.26095672 0.6084737  0.1966518  0.37782654 0.06241541 0.61346625]

Lambda 6: 28.73765203645719
v 6: [0.31984414 0.6109336  0.27084245 0.43289088 0.13500942 0.49546158]

Lambda 7: 28.86060748894485
v 7: [0.27359791 0.61150362 0.21221547 0.39404756 0.07857305 0.58713277]

Lambda 8: 28.934206623735413
v 8: [0.30897857 0.61258148 0.25709221 0.42597969 0.12207069 0.51654605]

Lambda 9: 28.97820583638576
v 9: [0.28152708 0.61257866 0.22218359 0.40232792 0.08843555 

### 18 more iterations for a lower tolerance

In [38]:
# power iteration with v02 and tolerance 10^-6
l_p2_1, v_p2_1 = poweriter(A, v02, 10**-6)

Lambda 0: 604.0
v 0: [ 0.31622777  0.79056942  0.47434165  0.         -0.15811388  0.15811388]

Lambda 1: 26.298838587342964
v 1: [0.41999108 0.48195698 0.1032765  0.33048479 0.0826212  0.68162487]

Lambda 2: 28.214385800638166
v 2: [0.32699814 0.62446884 0.34310402 0.38336872 0.12884703 0.47097493]

Lambda 3: 28.64118779053343
v 3: [0.2875921  0.59222814 0.20370755 0.37389339 0.07560341 0.61607443]

Lambda 4: 28.814984567706173
v 4: [0.31845284 0.61108348 0.27566305 0.42055017 0.12932295 0.50555689]

Lambda 5: 28.908797518491042
v 5: [0.28029731 0.60913328 0.21785052 0.39373827 0.08326618 0.58392477]

Lambda 6: 28.96337467412309
v 6: [0.30780302 0.61221134 0.2561132  0.42209397 0.11940836 0.52195684]

Lambda 7: 28.995707221246185
v 7: [0.28406117 0.61219703 0.22504064 0.40306731 0.09077616 0.56848675]

Lambda 8: 29.014955659995998
v 8: [0.30168065 0.61294008 0.24778856 0.41953382 0.11283858 0.53212113]

Lambda 9: 29.026431833219874
v 9: [0.28756868 0.61290565 0.22976767 0.40761578 0.0

In [39]:
# power iteration with v02 and tolerance 10^-10
l_p2_2, v_p2_2 = poweriter(A, v02, 10**-10)

Lambda 0: 604.0
v 0: [ 0.31622777  0.79056942  0.47434165  0.         -0.15811388  0.15811388]

Lambda 1: 26.298838587342964
v 1: [0.41999108 0.48195698 0.1032765  0.33048479 0.0826212  0.68162487]

Lambda 2: 28.214385800638166
v 2: [0.32699814 0.62446884 0.34310402 0.38336872 0.12884703 0.47097493]

Lambda 3: 28.64118779053343
v 3: [0.2875921  0.59222814 0.20370755 0.37389339 0.07560341 0.61607443]

Lambda 4: 28.814984567706173
v 4: [0.31845284 0.61108348 0.27566305 0.42055017 0.12932295 0.50555689]

Lambda 5: 28.908797518491042
v 5: [0.28029731 0.60913328 0.21785052 0.39373827 0.08326618 0.58392477]

Lambda 6: 28.96337467412309
v 6: [0.30780302 0.61221134 0.2561132  0.42209397 0.11940836 0.52195684]

Lambda 7: 28.995707221246185
v 7: [0.28406117 0.61219703 0.22504064 0.40306731 0.09077616 0.56848675]

Lambda 8: 29.014955659995998
v 8: [0.30168065 0.61294008 0.24778856 0.41953382 0.11283858 0.53212113]

Lambda 9: 29.026431833219874
v 9: [0.28756868 0.61290565 0.22976767 0.40761578 0.0

### 17 more iterations for a lower tolerance

In [40]:
# inverse iteration with v01, mu = 10 and tolerance 10^-6
l_i111, v_i111 = inverseiter(A, v01, 10, 10**-6)

Lambda 0: 10
v 0: [0.40824829 0.40824829 0.40824829 0.40824829 0.40824829 0.40824829]

Lambda 1: 11.034259967369438
v 1: [ 0.03191823  0.50873179 -0.23792092 -0.48463665  0.65840819  0.12325905]

Lambda 2: 10.321965425824418
v 2: [-0.14131754  0.38733009 -0.32991764 -0.43221658  0.73071903 -0.01994073]

Lambda 3: 10.321298060011843
v 3: [-0.1442638   0.39126247 -0.33876583 -0.4281937   0.72611113 -0.02742506]

Lambda 4: 10.321295051628622
v 4: [-0.14484663  0.39132626 -0.33908504 -0.42758174  0.72616478 -0.02762448]



In [41]:
# inverse iteration with v01, mu = 10 and tolerance 10^-10
l_i112, v_i112 = inverseiter(A, v01, 10, 10**-10)

Lambda 0: 10
v 0: [0.40824829 0.40824829 0.40824829 0.40824829 0.40824829 0.40824829]

Lambda 1: 11.034259967369438
v 1: [ 0.03191823  0.50873179 -0.23792092 -0.48463665  0.65840819  0.12325905]

Lambda 2: 10.321965425824418
v 2: [-0.14131754  0.38733009 -0.32991764 -0.43221658  0.73071903 -0.01994073]

Lambda 3: 10.321298060011843
v 3: [-0.1442638   0.39126247 -0.33876583 -0.4281937   0.72611113 -0.02742506]

Lambda 4: 10.321295051628622
v 4: [-0.14484663  0.39132626 -0.33908504 -0.42758174  0.72616478 -0.02762448]

Lambda 5: 10.321295034545377
v 5: [-0.1448645   0.39134953 -0.33912169 -0.42754746  0.72615077 -0.0276501 ]



### 1 more iterations for a lower tolerance

In [42]:
# inverse iteration with v01, mu = 40 and tolerance 10^-6
l_i121, v_i121 = inverseiter(A, v01, 40, 10**-6)

Lambda 0: 40
v 0: [0.40824829 0.40824829 0.40824829 0.40824829 0.40824829 0.40824829]

Lambda 1: 28.60563469213931
v 1: [-0.32826052 -0.56063716 -0.29658237 -0.38718235 -0.19151258 -0.55080184]

Lambda 2: 29.006506507152828
v 2: [0.30499376 0.59713535 0.25811181 0.39526103 0.12866895 0.55767329]

Lambda 3: 29.038590932193912
v 3: [-0.29817896 -0.60773786 -0.24532851 -0.40412298 -0.11112101 -0.55307745]

Lambda 4: 29.04263280073497
v 4: [0.29560146 0.61120483 0.24058616 0.40907799 0.10579949 0.55011671]

Lambda 5: 29.043268547863885
v 5: [-0.29446503 -0.61243735 -0.23869703 -0.41143941 -0.10406151 -0.5487471 ]

Lambda 6: 29.04337724889117
v 6: [0.29394106 0.61290474 0.23791654 0.41249951 0.10346145 0.54816241]

Lambda 7: 29.04339647817395
v 7: [-0.29369976 -0.61309058 -0.23758816 -0.41296305 -0.10324582 -0.54791795]

Lambda 8: 29.04339993525744
v 8: [0.29359009 0.61316692 0.23744866 0.41316318 0.10316604 0.54781591]



In [43]:
# inverse iteration with v01, mu = 40 and tolerance 10^-10
l_i122, v_i122 = inverseiter(A, v01, 40, 10**-10)

Lambda 0: 40
v 0: [0.40824829 0.40824829 0.40824829 0.40824829 0.40824829 0.40824829]

Lambda 1: 28.60563469213931
v 1: [-0.32826052 -0.56063716 -0.29658237 -0.38718235 -0.19151258 -0.55080184]

Lambda 2: 29.006506507152828
v 2: [0.30499376 0.59713535 0.25811181 0.39526103 0.12866895 0.55767329]

Lambda 3: 29.038590932193912
v 3: [-0.29817896 -0.60773786 -0.24532851 -0.40412298 -0.11112101 -0.55307745]

Lambda 4: 29.04263280073497
v 4: [0.29560146 0.61120483 0.24058616 0.40907799 0.10579949 0.55011671]

Lambda 5: 29.043268547863885
v 5: [-0.29446503 -0.61243735 -0.23869703 -0.41143941 -0.10406151 -0.5487471 ]

Lambda 6: 29.04337724889117
v 6: [0.29394106 0.61290474 0.23791654 0.41249951 0.10346145 0.54816241]

Lambda 7: 29.04339647817395
v 7: [-0.29369976 -0.61309058 -0.23758816 -0.41296305 -0.10324582 -0.54791795]

Lambda 8: 29.04339993525744
v 8: [0.29359009 0.61316692 0.23744866 0.41316318 0.10316604 0.54781591]

Lambda 9: 29.043400562101493
v 9: [-0.29354092 -0.61319896 -0.23738908

### 6 more iterations for a lower tolerance

In [44]:
# inverse iteration with v02, mu = 10 and tolerance 10^-6
l_i211, v_i211 = inverseiter(A, v02, 10, 10**-6)

Lambda 0: 10
v 0: [ 0.31622777  0.79056942  0.47434165  0.         -0.15811388  0.15811388]

Lambda 1: 10.599509993109319
v 1: [ 0.15803588 -0.42459327  0.52225504  0.34120865  0.01944122  0.63654817]

Lambda 2: 10.316447887425824
v 2: [ 0.2036607  -0.37111469  0.35427759  0.37644796 -0.7433075   0.0326264 ]

Lambda 3: 10.321315070368604
v 3: [ 0.14515034 -0.3936324   0.34223976  0.42576966 -0.72434149  0.03010742]

Lambda 4: 10.321295283527753
v 4: [ 0.14509347 -0.39137031  0.33922257  0.42730746 -0.72618604  0.02770157]



In [45]:
# inverse iteration with v02, mu = 10 and tolerance 10^-10
l_i212, v_i212 = inverseiter(A, v02, 10, 10**-10)

Lambda 0: 10
v 0: [ 0.31622777  0.79056942  0.47434165  0.         -0.15811388  0.15811388]

Lambda 1: 10.599509993109319
v 1: [ 0.15803588 -0.42459327  0.52225504  0.34120865  0.01944122  0.63654817]

Lambda 2: 10.316447887425824
v 2: [ 0.2036607  -0.37111469  0.35427759  0.37644796 -0.7433075   0.0326264 ]

Lambda 3: 10.321315070368604
v 3: [ 0.14515034 -0.3936324   0.34223976  0.42576966 -0.72434149  0.03010742]

Lambda 4: 10.321295283527753
v 4: [ 0.14509347 -0.39137031  0.33922257  0.42730746 -0.72618604  0.02770157]

Lambda 5: 10.321295036149527
v 5: [ 0.14487243 -0.3913598   0.33913756  0.42753218 -0.72614482  0.02766104]

Lambda 6: 10.321295034460974
v 6: [ 0.1448681  -0.39135079  0.33912442  0.42754303 -0.72615064  0.02765175]



### 2 more iterations for a lower tolerance

In [46]:
# inverse iteration with v02, mu = 40 and tolerance 10^-6
l_i221, v_i221 = inverseiter(A, v02, 10, 10**-6)

Lambda 0: 10
v 0: [ 0.31622777  0.79056942  0.47434165  0.         -0.15811388  0.15811388]

Lambda 1: 10.599509993109319
v 1: [ 0.15803588 -0.42459327  0.52225504  0.34120865  0.01944122  0.63654817]

Lambda 2: 10.316447887425824
v 2: [ 0.2036607  -0.37111469  0.35427759  0.37644796 -0.7433075   0.0326264 ]

Lambda 3: 10.321315070368604
v 3: [ 0.14515034 -0.3936324   0.34223976  0.42576966 -0.72434149  0.03010742]

Lambda 4: 10.321295283527753
v 4: [ 0.14509347 -0.39137031  0.33922257  0.42730746 -0.72618604  0.02770157]



In [47]:
# inverse iteration with v02, mu = 40 and tolerance 10^-10
l_i222, v_i222 = inverseiter(A, v02, 40, 10**-10)

Lambda 0: 40
v 0: [ 0.31622777  0.79056942  0.47434165  0.         -0.15811388  0.15811388]

Lambda 1: 27.609805494781202
v 1: [-0.3528116  -0.69007496 -0.32371574 -0.27117643 -0.0164817  -0.46980883]

Lambda 2: 28.927493676833137
v 2: [0.32363734 0.63092775 0.26408223 0.36572736 0.07955713 0.53606323]

Lambda 3: 29.031747091438106
v 3: [-0.30631741 -0.61599424 -0.24670281 -0.39615024 -0.09692799 -0.54729189]

Lambda 4: 29.04191262616834
v 4: [0.298713   0.61312173 0.24103474 0.40677541 0.10156415 0.54861009]

Lambda 5: 29.043175712040885
v 5: [-0.29559771 -0.61283999 -0.23890057 -0.41072523 -0.102764   -0.54837944]

Lambda 6: 29.043363244807985
v 6: [0.29434677 0.6129684  0.23801907 0.41226108 0.10305562 0.54808482]

Lambda 7: 29.043394148911037
v 7: [-0.29384524 -0.61308938 -0.23763914 -0.41287766 -0.10311685 -0.54790782]

Lambda 8: 29.043399526859602
v 8: [0.29364285 0.61315895 0.23747306 0.4131307  0.10312457 0.54781829]

Lambda 9: 29.043400488590745
v 9: [-0.29356039 -0.6131936  -

### 10 more iterations for a lower tolerance

In [48]:
# Rayleigh quotient iteration with v01, mu = 10 and tolerance 10^-6
l_r111, v_r111 = rayleigh(A, v01, 10, 10**-6)

Lambda 0: 10
v 0: [0.40824829 0.40824829 0.40824829 0.40824829 0.40824829 0.40824829]

Lambda 1: 11.034259967369438
v 1: [ 0.03191823  0.50873179 -0.23792092 -0.48463665  0.65840819  0.12325905]

Lambda 2: 10.327400178566965
v 2: [ 0.15760338 -0.4011504   0.3628408   0.41092895 -0.71519675  0.047086  ]

Lambda 3: 10.321295046508185
v 3: [-0.14483604  0.39134158 -0.33909999 -0.42758089  0.72615172 -0.02763591]



In [49]:
# Rayleigh quotient iteration with v01, mu = 10 and tolerance 10^-10
l_r112, v_r112 = rayleigh(A, v01, 10, 10**-10)

Lambda 0: 10
v 0: [0.40824829 0.40824829 0.40824829 0.40824829 0.40824829 0.40824829]

Lambda 1: 11.034259967369438
v 1: [ 0.03191823  0.50873179 -0.23792092 -0.48463665  0.65840819  0.12325905]

Lambda 2: 10.327400178566965
v 2: [ 0.15760338 -0.4011504   0.3628408   0.41092895 -0.71519675  0.047086  ]

Lambda 3: 10.321295046508185
v 3: [-0.14483604  0.39134158 -0.33909999 -0.42758089  0.72615172 -0.02763591]

Lambda 4: 10.321295034451008
v 4: [ 0.14486714 -0.39135051  0.33912377  0.42754417 -0.72615063  0.02765137]



### 1 more iterations for a lower tolerance

In [50]:
# Rayleigh quotient iteration with v01, mu = 40 and tolerance 10^-6
l_r121, v_r121 = rayleigh(A, v01, 40, 10**-6)

Lambda 0: 40
v 0: [0.40824829 0.40824829 0.40824829 0.40824829 0.40824829 0.40824829]

Lambda 1: 28.60563469213931
v 1: [-0.32826052 -0.56063716 -0.29658237 -0.38718235 -0.19151258 -0.55080184]

Lambda 2: 29.043246030820214
v 2: [-0.29266136 -0.61421252 -0.23592114 -0.41473226 -0.10157208 -0.54691297]

Lambda 3: 29.043400701852136
v 3: [-0.29350218 -0.61322283 -0.23734431 -0.41331309 -0.10311672 -0.54774186]



In [51]:
# Rayleigh quotient iteration with v01, mu = 40 and tolerance 10^-10
l_r122, v_r122 = rayleigh(A, v01, 40, 10**-10)

Lambda 0: 40
v 0: [0.40824829 0.40824829 0.40824829 0.40824829 0.40824829 0.40824829]

Lambda 1: 28.60563469213931
v 1: [-0.32826052 -0.56063716 -0.29658237 -0.38718235 -0.19151258 -0.55080184]

Lambda 2: 29.043246030820214
v 2: [-0.29266136 -0.61421252 -0.23592114 -0.41473226 -0.10157208 -0.54691297]

Lambda 3: 29.043400701852136
v 3: [-0.29350218 -0.61322283 -0.23734431 -0.41331309 -0.10311672 -0.54774186]



### 0 more iterations for a lower tolerance

In [52]:
# Rayleigh quotient iteration with v02, mu = 10 and tolerance 10^-6
l_r211, v_r211 = rayleigh(A, v02, 10, 10**-6)

Lambda 0: 10
v 0: [ 0.31622777  0.79056942  0.47434165  0.         -0.15811388  0.15811388]

Lambda 1: 10.599509993109319
v 1: [ 0.15803588 -0.42459327  0.52225504  0.34120865  0.01944122  0.63654817]

Lambda 2: 10.324225797013346
v 2: [-0.09188575  0.40276523 -0.31857418 -0.47292621  0.7098078  -0.01900924]

Lambda 3: 10.321295039255949
v 3: [ 0.14487491 -0.39136953  0.33915144  0.42752409 -0.72613693  0.02767245]



In [53]:
# Rayleigh quotient iteration with v02, mu = 10 and tolerance 10^-10
l_r212, v_r212 = rayleigh(A, v02, 10, 10**-10)

Lambda 0: 10
v 0: [ 0.31622777  0.79056942  0.47434165  0.         -0.15811388  0.15811388]

Lambda 1: 10.599509993109319
v 1: [ 0.15803588 -0.42459327  0.52225504  0.34120865  0.01944122  0.63654817]

Lambda 2: 10.324225797013346
v 2: [-0.09188575  0.40276523 -0.31857418 -0.47292621  0.7098078  -0.01900924]

Lambda 3: 10.321295039255949
v 3: [ 0.14487491 -0.39136953  0.33915144  0.42752409 -0.72613693  0.02767245]

Lambda 4: 10.321295034451014
v 4: [-0.14486714  0.39135051 -0.33912377 -0.42754417  0.72615063 -0.02765137]



### 1 more iterations for a lower tolerance

In [54]:
# Rayleigh quotient iteration with v02, mu = 40 and tolerance 10^-6
l_r221, v_r221 = rayleigh(A, v02, 40, 10**-6)

Lambda 0: 40
v 0: [ 0.31622777  0.79056942  0.47434165  0.         -0.15811388  0.15811388]

Lambda 1: 27.609805494781202
v 1: [-0.3528116  -0.69007496 -0.32371574 -0.27117643 -0.0164817  -0.46980883]

Lambda 2: 29.03842533148632
v 2: [-0.28590451 -0.61040106 -0.23113931 -0.42390046 -0.10740493 -0.54864958]

Lambda 3: 29.043400701537806
v 3: [-0.29350454 -0.61322273 -0.23734609 -0.41331008 -0.10311608 -0.54774232]



In [55]:
# Rayleigh quotient iteration with v02, mu = 40 and tolerance 10^-10
l_r222, v_r222 = rayleigh(A, v02, 40, 10**-10)

Lambda 0: 40
v 0: [ 0.31622777  0.79056942  0.47434165  0.         -0.15811388  0.15811388]

Lambda 1: 27.609805494781202
v 1: [-0.3528116  -0.69007496 -0.32371574 -0.27117643 -0.0164817  -0.46980883]

Lambda 2: 29.03842533148632
v 2: [-0.28590451 -0.61040106 -0.23113931 -0.42390046 -0.10740493 -0.54864958]

Lambda 3: 29.043400701537806
v 3: [-0.29350454 -0.61322273 -0.23734609 -0.41331008 -0.10311608 -0.54774232]

Lambda 4: 29.043400701852146
v 4: [-0.29350217 -0.61322284 -0.2373443  -0.41331311 -0.10311671 -0.54774185]



### 1 more iterations for a lower tolerance

In [56]:
names = ['p(1, ,1)', 'p(1, ,2)', 'p(2, ,1)', 'p(2, ,2)', 
         'i(1,1,1)', 'i(1,1,2)', 'i(1,2,1)', 'i(1,2,2)', 
         'i(2,1,1)', 'i(2,1,2)', 'i(2,2,1)', 'i(2,2,2)', 
         'r(1,1,1)', 'r(1,1,2)', 'r(1,2,1)', 'r(1,2,2)', 
         'r(2,1,1)', 'r(2,1,2)', 'r(2,2,1)', 'r(2,2,2)']

In [57]:
lams = [l_p1_1, l_p1_2, l_p2_1, l_p2_2, 
        l_i111, l_i112, l_i121, l_i122, 
        l_i211, l_i212, l_i221, l_i222, 
        l_r111, l_r112, l_r121, l_r122, 
        l_r211, l_r212, l_r221, l_r222]

In [58]:
vecs = [v_p1_1, v_p1_2, v_p2_1, v_p2_2, 
        v_i111, v_i112, v_i121, v_i122, 
        v_i211, v_i212, v_i221, v_i222, 
        v_r111, v_r112, v_r121, v_r122, 
        v_r211, v_r212, v_r221, v_r222]

### Notation: (initial vector number, initial mu, tolerance)
1 means v01, mu = 10, or tolerance = 10^-6, respectively

2 means v02, mu = 40, or tolerance = 10^-10, respectively

In [59]:
for n, l in zip(names, lams):
    print('{} eigenvalue: {}'.format(n, l))

p(1, ,1) eigenvalue: 29.043399432355013
p(1, ,2) eigenvalue: 29.043400701735862
p(2, ,1) eigenvalue: 29.04339977443059
p(2, ,2) eigenvalue: 29.043400701709754
i(1,1,1) eigenvalue: 10.321295034545377
i(1,1,2) eigenvalue: 10.32129503445152
i(1,2,1) eigenvalue: 29.043400562101493
i(1,2,2) eigenvalue: 29.04340070184686
i(2,1,1) eigenvalue: 10.321295036149527
i(2,1,2) eigenvalue: 10.321295034451065
i(2,2,1) eigenvalue: 10.321295036149527
i(2,2,2) eigenvalue: 29.043400701844057
r(1,1,1) eigenvalue: 10.321295034451008
r(1,1,2) eigenvalue: 10.32129503445101
r(1,2,1) eigenvalue: 29.043400701852143
r(1,2,2) eigenvalue: 29.043400701852143
r(2,1,1) eigenvalue: 10.321295034451014
r(2,1,2) eigenvalue: 10.321295034451012
r(2,2,1) eigenvalue: 29.043400701852146
r(2,2,2) eigenvalue: 29.043400701852146


In [60]:
for n, v in zip(names, vecs):
    print('{} eigenvector: \n{}'.format(n, v[:, None]))

p(1, ,1) eigenvector: 
[[0.29355488]
 [0.61322354]
 [0.23741132]
 [0.41335938]
 [0.10318139]
 [0.54763665]]
p(1, ,2) eigenvector: 
[[0.29350267]
 [0.61322284]
 [0.23734494]
 [0.41331355]
 [0.10311733]
 [0.54774084]]
p(2, ,1) eigenvector: 
[[0.29354722]
 [0.61322344]
 [0.23740158]
 [0.41335266]
 [0.103172  ]
 [0.54765194]]
p(2, ,2) eigenvector: 
[[0.29350161]
 [0.61322283]
 [0.23734359]
 [0.41331261]
 [0.10311603]
 [0.54774296]]
i(1,1,1) eigenvector: 
[[-0.1448645 ]
 [ 0.39134953]
 [-0.33912169]
 [-0.42754746]
 [ 0.72615077]
 [-0.0276501 ]]
i(1,1,2) eigenvector: 
[[-0.14486701]
 [ 0.3913504 ]
 [-0.33912359]
 [-0.42754438]
 [ 0.72615069]
 [-0.02765125]]
i(1,2,1) eigenvector: 
[[-0.29354092]
 [-0.61319896]
 [-0.23738908]
 [-0.41324904]
 [-0.10313586]
 [-0.54777314]]
i(1,2,2) eigenvector: 
[[-0.29350242]
 [-0.61322268]
 [-0.23734458]
 [-0.41331272]
 [-0.1031168 ]
 [-0.54774204]]
i(2,1,1) eigenvector: 
[[ 0.14487243]
 [-0.3913598 ]
 [ 0.33913756]
 [ 0.42753218]
 [-0.72614482]
 [ 0.02766104]