In [1]:
import numpy as np
from scipy.linalg import null_space

In [2]:
def gs(A: np.array):
    m, n = A.shape

    Q = np.zeros((m, n))
    R = np.zeros((n, n))
    
    for i in range(0, n):
        v = A[:, i].copy()
        for j in range(i):
            R[j, i] = np.vdot(Q[:, j], A[:, i])
            v -= R[j, i] * Q[:, j]
        
        R[i, i] = np.linalg.norm(v)
        if R[i, i] == 0: 
            # pick an arbitrary q_i orthogonal to q1 to q_i-1
            Q_before_i = Q[:, :i].T.copy()
            Q[:, i] = null_space(Q_before_i)[0]
        else: 
            Q[:, i] = v / R[i, i]
    
    E = Q.T @ Q - np.eye(3)
    return Q, R, E

In [3]:
def mgs(A: np.array):
    m, n = A.shape

    Q = np.zeros((m, n))
    R = np.zeros((n, n))
    
    for i in range(0, n):
        v = A[:, i].copy()
        for j in range(i):
            R[j, i] = np.vdot(Q[:, j], v)
            v -= R[j, i] * Q[:, j]
        
        R[i, i] = np.linalg.norm(v)
        if R[i, i] == 0: 
            # pick an arbitrary q_i orthogonal to q1 to q_i-1
            Q_before_i = Q[:, :i].T.copy()
            Q[:, i] = null_space(Q_before_i)[0]
        else: 
            Q[:, i] = v / R[i, i]
            
    E = Q.T @ Q - np.eye(3)
    return Q, R, E

In [4]:
if __name__ == '__main__' and '__file__' not in globals():
    result = 'Q = \n {}\n\nR = \n{}' + \
            '\n\nLoss of Orthogonality = \n{}'
    for c in (-2, -4, -6, -8, -10):
        print('\u03B5 = 10^{}\n'.format(c))
        A = np.ones((3, 3))
        e = 10**c
        A[np.triu_indices(3, k=1)] += [e, 2*e, e]
        print('Classical Gram-Schmidt\n')
        print(result.format(*gs(A)))
        print('\nModified Gram-Schmidt\n')
        print(result.format(*mgs(A)))
        print('\n' + '-' * 80 + '\n\n')

ε = 10^-2

Classical Gram-Schmidt

Q = 
 [[ 5.77350269e-01  8.16496581e-01  1.27206928e-11]
 [ 5.77350269e-01 -4.08248290e-01  7.07106781e-01]
 [ 5.77350269e-01 -4.08248290e-01 -7.07106781e-01]]

R = 
[[1.73205081 1.73782431 1.74937132]
 [0.         0.00816497 0.01224745]
 [0.         0.         0.00707107]]

Loss of Orthogonality = 
[[ 2.22044605e-16 -6.27947491e-14  5.43805721e-14]
 [-6.27947491e-14  2.22044605e-16  1.55411449e-11]
 [ 5.43805721e-14  1.55411449e-11  0.00000000e+00]]

Modified Gram-Schmidt

Q = 
 [[ 5.77350269e-01  8.16496581e-01  3.11565222e-14]
 [ 5.77350269e-01 -4.08248290e-01  7.07106781e-01]
 [ 5.77350269e-01 -4.08248290e-01 -7.07106781e-01]]

R = 
[[1.73205081 1.73782431 1.74937132]
 [0.         0.00816497 0.01224745]
 [0.         0.         0.00707107]]

Loss of Orthogonality = 
[[ 2.22044605e-16 -6.27947491e-14  5.43709336e-14]
 [-6.27947491e-14  2.22044605e-16 -3.20266817e-16]
 [ 5.43709336e-14 -3.20266817e-16  0.00000000e+00]]

------------------------------