In [1]:
import numpy as np
from numpy.linalg import norm, qr
import matplotlib.pyplot as plt
%run Gram_Schmidt_Orthogonalization.ipynb
np.set_printoptions(precision=10)

In [2]:
def house(A):
    m, n = A.shape
    if m < n: 
        raise np.linalg.LinAigError(
            'Input column vectors not all linearly independent')
    
    R = A.copy()
    Q = np.eye(m)
    for k, a in enumerate(R.T):
        v = - a[k:].copy()
        # sign(v[0]) was reversed
        v[0] += np.sign(v[0]) * norm(v)
        v = v / norm(v)
        R[k:, k:] -= 2 * np.outer(v, v) @ R[k:, k:]
        Q[:, k:] -= 2 * Q[:, k:] @ np.outer(v, v)
    
    E = Q.T @ Q - np.eye(m)
    return Q, R, E

In [3]:
Z = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 7], 
             [4, 2, 3], [4, 2, 2]], dtype='float64')

A = np.ones((3, 3))
A[np.triu_indices(3, k=1)] += [1e-4, 2e-4, 1e-4]

B = np.ones((3, 3))
B[np.triu_indices(3, k=1)] += [1e-10, 2e-10, 1e-10]

In [4]:
result = 'Q = \n {}\n\nR = \n{}' + \
        '\n\nLoss of Orthogonality = \n{}'

In [5]:
for x in (Z, A, B):
    print('Input: \n', x, '\n\n')
    Q, R, E = house(x)
    print(result.format(Q, R, E))
    print('-' * 70)

Input: 
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 7.]
 [4. 2. 3.]
 [4. 2. 2.]] 


Q = 
 [[-0.1010152545 -0.3161730695  0.5419968999 -0.6842084629 -0.3576711454]
 [-0.4040610178 -0.3533699012  0.5161875237  0.3280084066  0.581227436 ]
 [-0.7071067812 -0.3905667329 -0.5247906491  0.0093972166 -0.2682612422]
 [-0.4040610178  0.5579524756  0.3871406428  0.3655972729 -0.4918175328]
 [-0.4040610178  0.5579524756 -0.1204437555 -0.5389986928  0.469465057 ]]

R = 
[[-9.8994949366e+00 -9.4954339188e+00 -9.6974644277e+00]
 [-8.8817841970e-16 -3.2919196062e+00 -3.0129433684e+00]
 [ 0.0000000000e+00  0.0000000000e+00  1.9701157154e+00]
 [-8.8817841970e-16  0.0000000000e+00  1.1102230246e-16]
 [-8.8817841970e-16  0.0000000000e+00 -5.5511151231e-17]]

Loss of Orthogonality = 
[[ 0.0000000000e+00  5.1509121596e-17 -1.3672188521e-16  3.8402565205e-17
   8.1285975971e-18]
 [ 5.1509121596e-17  0.0000000000e+00 -3.2119882652e-17 -3.9491564177e-17
  -9.0317722953e-17]
 [-1.3672188521e-16 -3.2119882652e-17 -8.881784

In [6]:
for x in (Z, A, B):
    print('Input: \n', x, '\n\n')
    Q, R, E = gs(x)
    print(result.format(Q, R, E))
    print('-' * 70)

Input: 
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 7.]
 [4. 2. 3.]
 [4. 2. 2.]] 


Q = 
 [[ 0.1010152545  0.3161730695  0.5419968999]
 [ 0.4040610178  0.3533699012  0.5161875237]
 [ 0.7071067812  0.3905667329 -0.5247906491]
 [ 0.4040610178 -0.5579524756  0.3871406428]
 [ 0.4040610178 -0.5579524756 -0.1204437555]]

R = 
[[9.8994949366 9.4954339188 9.6974644277]
 [0.           3.2919196062 3.0129433684]
 [0.           0.           1.9701157154]]

Loss of Orthogonality = 
[[ 0.0000000000e+00  2.3191095063e-16  5.2589450093e-17]
 [ 2.3191095063e-16  2.2204460493e-16 -1.3166270082e-15]
 [ 5.2589450093e-17 -1.3166270082e-15 -2.2204460493e-16]]
----------------------------------------------------------------------
Input: 
 [[1.     1.0001 1.0002]
 [1.     1.     1.0001]
 [1.     1.     1.    ]] 


Q = 
 [[ 5.7735026919e-01  8.1649658093e-01  9.4217121586e-08]
 [ 5.7735026919e-01 -4.0824829047e-01  7.0710673408e-01]
 [ 5.7735026919e-01 -4.0824829047e-01 -7.0710682829e-01]]

R = 
[[1.7320508076e+00 1.732

In [7]:
for x in (Z, A, B):
    print('Input: \n', x, '\n\n')
    Q, R, E = mgs(x)
    print(result.format(Q, R, E))
    print('-' * 70)

Input: 
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 7.]
 [4. 2. 3.]
 [4. 2. 2.]] 


Q = 
 [[ 0.1010152545  0.3161730695  0.5419968999]
 [ 0.4040610178  0.3533699012  0.5161875237]
 [ 0.7071067812  0.3905667329 -0.5247906491]
 [ 0.4040610178 -0.5579524756  0.3871406428]
 [ 0.4040610178 -0.5579524756 -0.1204437555]]

R = 
[[9.8994949366 9.4954339188 9.6974644277]
 [0.           3.2919196062 3.0129433684]
 [0.           0.           1.9701157154]]

Loss of Orthogonality = 
[[ 0.0000000000e+00  2.3191095063e-16  2.0621721935e-16]
 [ 2.3191095063e-16  2.2204460493e-16 -4.1659030719e-16]
 [ 2.0621721935e-16 -4.1659030719e-16 -1.1102230246e-16]]
----------------------------------------------------------------------
Input: 
 [[1.     1.0001 1.0002]
 [1.     1.     1.0001]
 [1.     1.     1.    ]] 


Q = 
 [[ 5.7735026919e-01  8.1649658093e-01  1.5702841204e-12]
 [ 5.7735026919e-01 -4.0824829047e-01  7.0710678119e-01]
 [ 5.7735026919e-01 -4.0824829047e-01 -7.0710678118e-01]]

R = 
[[1.7320508076e+00 1.732

### Use the built-in Numpy algorithm qr instead of that of Matlab algorithm

In [8]:
for x in (Z, A, B):
    print('Input: \n', x, '\n\n')
    Q, R = qr(x)
    E = Q.T @ Q - np.eye(Q.shape[1])
    print(result.format(Q, R, E))
    print('-' * 70)

Input: 
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 7.]
 [4. 2. 3.]
 [4. 2. 2.]] 


Q = 
 [[-0.1010152545 -0.3161730695  0.5419968999]
 [-0.4040610178 -0.3533699012  0.5161875237]
 [-0.7071067812 -0.3905667329 -0.5247906491]
 [-0.4040610178  0.5579524756  0.3871406428]
 [-0.4040610178  0.5579524756 -0.1204437555]]

R = 
[[-9.8994949366 -9.4954339188 -9.6974644277]
 [ 0.           -3.2919196062 -3.0129433684]
 [ 0.            0.            1.9701157154]]

Loss of Orthogonality = 
[[-1.1102230246e-16  9.8663457008e-18  1.0050306102e-16]
 [ 9.8663457008e-18  0.0000000000e+00  1.4844838482e-17]
 [ 1.0050306102e-16  1.4844838482e-17  2.2204460493e-16]]
----------------------------------------------------------------------
Input: 
 [[1.     1.0001 1.0002]
 [1.     1.     1.0001]
 [1.     1.     1.    ]] 


Q = 
 [[-5.7735026919e-01  8.1649658093e-01 -8.7560529338e-17]
 [-5.7735026919e-01 -4.0824829046e-01 -7.0710678119e-01]
 [-5.7735026919e-01 -4.0824829046e-01  7.0710678119e-01]]

R = 
[[-1.7320508076

### Discussion
1. All entries of the matrices Q and R yielded by Householder Triangularization are opposite numbers of those in the Q and R yielded by Gram-Schmidt Orthogonalization. 
2. The upper triangular matrix achieved from Householder Triangularization algorithm is not perfectly upper triangular. 
3. Compared to Gram-Schmidt algorithm, Householder algorithm yields more precise orthogonal matrix Q, but not significantly. 