In [1]:
import numpy as np
from numpy.linalg import norm
np.set_printoptions(precision=5)

In [2]:
def gauss(A: np.array):
    m = A.shape[0]
    assert m == A.shape[1]
    
    L = np.identity(m)
    U = A.copy()
    for k in range(m-1):
        for i in range(k+1, m):
            L[i:, k] = U[i, k]/U[k, k]
            U[i] -= L[i, k]*U[k]
            
    return (L, U)

In [3]:
def gausspivot(A: np.array):
    m = A.shape[0]
    assert m == A.shape[1]
    
    L = np.identity(m)
    P = np.identity(m)
    U = A.copy()
    for k in range(m-1):
        i_max = np.argmax(A[k+1:, k]**2) + k + 1 # find arg max
        # swapping U P L        
        P[[k, i_max]] = P[[i_max, k]] 
        U[[k, i_max], k:] = U[[i_max, k], k:]
        L[[k, i_max], :k] = L[[i_max, k], :k]
        for i in range(k+1, m):
            L[i:, k] = U[i, k]/U[k, k]
            U[i] -= L[i, k]*U[k]
            
    return (L, U, P)

In [5]:
A = np.array([[-8, -9, 7, 19, 3],
             [9, 10, 9, 1, -16],
             [7, 2, -8, -2, 3],
             [19, 8, -18, -8, -3],
             [15, 10, 16, -16, -18]], dtype='float64')

In [6]:
L, U = gauss(A)
eps1 = norm(L@U - A)/norm(A)
print('L = \n{}\n\nU = \n{}\n\neps1 = {}'.format(L, U, eps1))

L = 
[[   1.         0.         0.         0.         0.     ]
 [  -1.125      1.         0.         0.         0.     ]
 [  -0.875     47.         1.         0.         0.     ]
 [  -2.375    107.         2.27296    1.         0.     ]
 [  -1.875     55.         1.13082 -692.77273    1.     ]]

U = 
[[-8.00000e+00 -9.00000e+00  7.00000e+00  1.90000e+01  3.00000e+00]
 [ 0.00000e+00 -1.25000e-01  1.68750e+01  2.23750e+01 -1.26250e+01]
 [ 0.00000e+00  0.00000e+00 -7.95000e+02 -1.03700e+03  5.99000e+02]
 [ 0.00000e+00  0.00000e+00  2.27374e-13  5.53459e-02 -6.50063e+00]
 [ 0.00000e+00  0.00000e+00  1.57518e-10  0.00000e+00 -4.49882e+03]]

eps1 = 4.5343471868882046e-15


In [7]:
L, U, P = gausspivot(A)
eps2 = norm(L@U - P@A)/norm(A)
print('L = \n{}\n\nU = \n{}\n\nP = \n{}\n\neps2 = {}'.format(L, U, P, eps2))

L = 
[[ 1.       0.       0.       0.       0.     ]
 [ 0.78947  1.       0.       0.       0.     ]
 [-0.42105 -1.52857  1.       0.       0.     ]
 [ 0.47368  1.68571 -0.73246  1.       0.     ]
 [ 0.36842 -0.25714  0.14035 -0.07638  1.     ]]

U = 
[[ 19.        8.      -18.       -8.       -3.     ]
 [  0.        3.68421  30.21053  -9.68421 -15.63158]
 [  0.        0.       45.6       0.82857 -22.15714]
 [  0.        0.        0.       21.72118  -4.45771]
 [  0.        0.        0.        0.        2.85499]]

P = 
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]

eps2 = 7.696662663893883e-17
